name: Ruby

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.2'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      # - name: Run RSpec tests task
      #   run: bundle exec rake spec
      - name: Run RuboCop
        run: bundle exec rubocop lib/ spec/ app/ --config .rubocop.yml
        # run: bundle exec rubocop --config .rubocop.yml
